name: aurigraph_sdk
description: Aurigraph DLT Flutter SDK for multi-platform blockchain development with quantum-resistant cryptography
version: 11.0.0
homepage: https://github.com/Aurigraph-DLT-Corp/Aurigraph-DLT
repository: https://github.com/Aurigraph-DLT-Corp/Aurigraph-DLT
issue_tracker: https://github.com/Aurigraph-DLT-Corp/Aurigraph-DLT/issues
documentation: https://docs.aurigraph.io/mobile-sdk/flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  crypto: ^3.0.3
  convert: ^3.1.1
  http: ^0.13.5
  local_auth: ^2.1.6
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  plugin:
    platforms:
      android:
        package: com.aurigraph.sdk.flutter
        pluginClass: AurigraphSdkPlugin
      ios:
        pluginClass: AurigraphSdkPlugin
      linux:
        pluginClass: AurigraphSdkPlugin
      macos:
        pluginClass: AurigraphSdkPlugin
      windows:
        pluginClass: AurigraphSdkPluginCApi

topics:
  - blockchain
  - cryptocurrency
  - aurigraph
  - quantum-resistant
  - defi
  - mobile-sdk

screenshots:
  - description: 'Wallet management interface'
    path: screenshots/wallet_management.png
  - description: 'Transaction history view'
    path: screenshots/transaction_history.png
  - description: 'Cross-chain bridge interface'
    path: screenshots/cross_chain_bridge.png