global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'validators'
    dns_sd_configs:
      - names:
          - 'validator'
        type: 'A'
        port: 9003
    metrics_path: '/q/metrics'

  - job_name: 'business_nodes'
    dns_sd_configs:
      - names:
          - 'business'
        type: 'A'
        port: 9009
    metrics_path: '/q/metrics'

  - job_name: 'slim_nodes'
    dns_sd_configs:
      - names:
          - 'slim'
        type: 'A'
        port: 9013
    metrics_path: '/q/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status' # Assuming you have ngx_http_stub_status_module enabled

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
